### ISSUE TITLE
Add a new property 'label' to categorize the data stores

### ISSUE THREAD

**Issue by airpingu** [airpingu/data-store-api#1]
We hope to add a new property `label` to categorize the data stores and use the original `name` to identify the data stores, so that the `getDataStores("foo")` will return an array of data stores that are labeled (categorized) as "foo".

For example, we can have the following data stores related to the messaging purpose:

```
  label: "messaging"
  name: "messaging-sms-sim-1"

  label: "messaging"
  name: "messaging-sms-sim-2"

  label: "messaging"
  name: "messaging-mms-sim-1"

  label: "messaging"
  name: "messaging-mms-sim-2"
```

Such that we can formally define the keyword "messaging" in the Messaging API spec as below:

  "Use `getDataStores("messaging")` to retrieve all the data stores that save messaging-related messages, like SMS or MMS. It's up to platform's implementation to decide whether or not to separate data stores to save different types of messages or different sources of messages. For example, SMS can be saved in one data store and MMS can be saved in another one; or just use single one to save both."

**Comment by zolkis** [comment]
We need to clarify the getDataStores signature and behavior then as well, because both labels and names could be input arguments to it.

**Comment by airpingu** [comment]
Will solve this by Tuesday and post the initiative version to the SysApps mailing list.

**Comment by airpingu** [comment]
Solved this at: https://github.com/airpingu/data-store-api/commit/807138f1ba6b0d4a8e08a3a291e5178c12267323
