### ISSUE TITLE
Discuss here or on mailing list?

### ISSUE THREAD

**Issue by tgvashworth** [airpingu/data-store-api#10]
> For more important contributions that require discussions, you are invited to start a thread in the sysapps mailing list at the W3C.

So you'd rather issues about the spec itself on the mailing list, not here?

**Comment by airpingu** [comment]
Thanks for the reminder. Actually, I'd like to work out a more solid version before proposing it on the sysapps mailing list (Mounir also suggested doing in this way). Hope I can finish all the issues this week.

**Comment by tgvashworth** [comment]
Ok, so if I want to contribute I should do it here? It just looked like you were saying discuss elsewhere :)

**Comment by airpingu** [comment]
Yeap, I'll take recent days to finalize the first version and post it to the SysApp mailing list ASAP. Will finish it by the next Tuesday and start with the discussion in public over there. Please stay tuned.

**Comment by airpingu** [comment]
I already post this to the SysApps public mailing list.
