### ISSUE TITLE
JSON manifest properties should be named as JavaScript properties

### ISSUE THREAD

**Issue by kenchris** [airpingu/data-store-api#13]
Thus "someProperty" and not "some_property" or "some-property"

**Comment by airpingu** [comment]
Is there any existing document supporting this? Just hope to clarify before modifying.

**Comment by airpingu** [comment]
I saw http://www.w3.org/2012/sysapps/manifest/ and http://w3c.github.io/manifest/ are still using "_", so I tentatively close this issue. Please correct me if I'm wrong. Thanks!
