### ISSUE TITLE
sync and revisionid

### ISSUE THREAD

**Issue by jmajnert** [airpingu/data-store-api#21]
How does the sync() method pass the new revisionId to the caller?

**Comment by airpingu** [comment]
The Promise resolver of `DataStoreCursor.next()` will return `DataStoreTask`[1] which contains a `revisionId` to specify the revision of each single change.

I'd like to close this one as wonfix. Please let me know if you disagree. Btw, may I have your full name again? I'd like to put your formal name in the acknowledgement. :)

[1] file:///home/gene/data-store-api/index.html#idl-def-DataStoreTask

**Comment by jmajnert** [comment]
Wouldn't it be better to somehow pass just the final (current) revisionId?
Why do I need to know that something was edited 3 revisions ago?
And by the way, how do I know which revisionId is the newest, from what I understand they don't need to be linear integers?

I updated my profile to include my name
