### ISSUE TITLE
using DataStoreCursor in DataStoreChangeEvent

### ISSUE THREAD

**Issue by jmajnert** [airpingu/data-store-api#25]
Wouldn't it be better to use DataStoreCursor inside the DataStoreChangeEvent ?

This would solve the problem of how to squash multiple updates into one change event and would also allow the client application to have just one code path for handling sync() method and onchange events.

**Comment by airpingu** [comment]
This is a very interesting idea. Will discuss with Mozilla internal to see if it's worth adding. Thanks for the suggestion!

**Comment by airpingu** [comment]
I think this exactly meets our design. In the onchange handler, the web content can call `sync()` to retrieve all the changes (note that the onchange handler won't be trigger when the `DataStoreCursor` is being used and its `close()` is not yet called).

So we don't need to change anything for this issue.

**Comment by jmajnert** [comment]
Are you sure this can be done without having to handle race conditions? Ex: What if there are two consecutive changes in the data store:
1. First change events is queued and fired. Onchange handler starts execution
2. Second change event is queued (not fired yet to JS).
3. Handler for first event calls sync() and retrieves all the changes. Then calls close() and exits
4. Second change event if fired to JS and onchange handler is run again?

**Comment by jmajnert** [comment]
Not relevant anymore
