### ISSUE TITLE
Use more specific function names like "insert" and "update".

### ISSUE THREAD

**Issue by airpingu** [airpingu/data-store-api#3]
Suggested by Zoltan: about merging `add` and `put` - they are different use cases with different error paths. The use case of "add if not exist" is a third one, resolving one error path of `update`. Let the user decide the behaviour, and it is probably safer to stick with the well-known separated `update` and `insert` semantics.

**Comment by zolkis** [comment]
See https://github.com/airpingu/data-store-api/issues/2#issuecomment-31110370

**Comment by airpingu** [comment]
Solved this at https://github.com/airpingu/data-store-api/issues/2#issuecomment-32703527 and close this one.
