### ISSUE TITLE
Elaborate more about the manifest settings for "datastores-access"

### ISSUE THREAD

**Issue by airpingu** [airpingu/data-store-api#5]
For example, the data store won't be read-only to the Messaging App which can claim the following entry in its manifest:

```
{
  datastores-access: {
    "messaging": {
      "access": "readwrite",
      "description": "access the messaging stores"
    }
  }
}
```

For other apps that just want to read the data store, it can simply claim:

```
{
  datastores-access: {
    "messaging": {
      "access": "readonly",
      "description": "access the messaging stores"
    }
  }
}
```

If the app doesn't claim the `datastores-access` entry in its manifest, the `getDataStores("messaging")` will return nothing to it, which means it can neither read or write the data stores.

**Comment by zolkis** [comment]
More exactly, the Promise resolves to an error.

**Comment by airpingu** [comment]
Solved this at https://github.com/airpingu/data-store-api/commit/1d61dce41152404ae327013ec7d3cbf88190b3ff.
